arrayan_gimnasio_homepage:
    pattern:  /
    defaults: { _controller: ArrayanGimnasioBundle:Default:index }

start:
    pattern: /start
    defaults: { _controller: ArrayanGimnasioBundle:Fitness:start }

feedback:
    pattern: /feedback/u/{hash}
    defaults: { _controller: ArrayanGimnasioBundle:Fitness:feedback }

feedback_send:
    pattern: /feedback/send
    defaults: { _controller: ArrayanGimnasioBundle:Fitness:feedback }
    requirements: { _method: post }

attainment:
    pattern: /attainment
    defaults: { _controller: ArrayanGimnasioBundle:Fitness:attainment }
